#version 460 core


layout(local_size_x=16, local_size_y=16) in;


#include "src/shaders/common.glsl"
#include "src/shaders/path_tracing/util_functions.glsl"
#include "src/shaders/path_tracing/bsdf_functions.glsl"
#include "src/shaders/path_tracing/intersect_functions.glsl"
#include "src/shaders/path_tracing/mis_functions.glsl"
#include "src/shaders/path_tracing/nee_functions.glsl"


PathSample PathTrace(Ray ray, inout uvec3 rng) {
    SurfaceInteraction si;

    si.mat.ior = 1.0;

    vec3 throughput = vec3(1.0);
    vec3 radiance = vec3(0.0);

    // Entry point of a ray travelling through a medium
    vec3 entryPoint = vec3(0.0);
    bool isInsideMedium = false;

    bool isFirstHit = true;

    PathSample pathSample;
    pathSample.baseCol = vec3(0.0);
    pathSample.normal = vec3(0.0);
    pathSample.depth = 0.0;
    pathSample.combined = vec3(0.0);

    float prevBsdfPdf = 0.0;
    vec3 prevPoint = vec3(0.0);

    BounceDepth bounceDepth;
    bounceDepth.diffuse = 0;
    bounceDepth.specular = 0;
    bounceDepth.transmission = 0;

    for (int i = 0; i <= maxTotalBounces; i++) {
        if (bounceDepth.diffuse > maxDiffuseBounces || 
            bounceDepth.specular > maxSpecularBounces || 
            bounceDepth.transmission > maxTransmissionBounces) {
            break;
        }

        if (!Intersect(ray, si)) {
            // Ray has exited the scene

            vec3 envColor = SampleHdri(ray.d);
            if (misMode == 0) {
                if (isFirstHit) {
                    radiance += throughput * envColor * hdriExposure;
                } else {
                    // Multiple Importance Sample (MIS)
                    // --------------------------------
                    float lightPdf = HdriPdf(ray.d);
                    float misWeight = PowerHeuristic(1, prevBsdfPdf, 1, lightPdf);
                    radiance += throughput * envColor * hdriExposure * misWeight;
                }
            } else if (misMode == 1) {
                radiance += throughput * envColor * hdriExposure;
            }

            break;
        }

        Triangle tri = triangles[si.triId];

        vec2 bary = si.bary;
        float u = bary.x;
        float v = bary.y;
        vec3 ng = si.ng;

        float w = 1.0 - u - v;
        vec2 texCoords = w * tri.v0.uv + u * tri.v1.uv + v * tri.v2.uv;

        vec3 ns = normalize(w * tri.v0.n + u * tri.v1.n + v * tri.v2.n);
        vec3 dpdu = normalize(w * tri.v0.dpdu + u * tri.v1.dpdu + v * tri.v2.dpdu);
        vec3 dpdv = normalize(w * tri.v0.dpdv + u * tri.v1.dpdv + v * tri.v2.dpdv);
        
        bool isBackFace = dot(ng, ray.d) > 0.0;

        if (isBackFace) {
            ng = -ng;
            ns = -ns;
            dpdu = -dpdu;
            dpdv = -dpdv;
        }

        Material mat = materials[tri.matId];

        float eta = isBackFace ? mat.ior / 1.0 : 1.0 / mat.ior;
        
        si.p = GetRayPoint(ray, si.t);
        si.ng = ng;
        si.ns = ns;
        si.dpdu = dpdu;
        si.dpdv = dpdv;
        si.uv = texCoords;
        si.eta = eta;
        si.isBackFace = isBackFace;
        si.area = tri.area;

        if (mat.hasBaseColTex == 1) {
            vec4 baseCol = texture(baseColorTextures, vec3(si.uv, mat.baseTexId));
            mat.baseCol = baseCol.rgb;
            mat.alpha = baseCol.w;
        }
        if (mat.hasEmissiveTex == 1) {
            mat.emissive = texture(emissiveTextures, vec3(si.uv, mat.emissiveTexId)).rgb;
        }
        if (mat.hasRoughTex == 1) {
            mat.roughness = texture(roughnessTextures, vec3(si.uv, mat.roughTexId)).r;
        }
        if (mat.hasMetalTex == 1) {
            mat.metallic = texture(metallicTextures, vec3(si.uv, mat.metalTexId)).r;
        }
        // https://learnopengl.com/Advanced-Lighting/Normal-Mapping
        if (mat.hasNormalTex == 1) {
            mat3 localToWorld = mat3(si.dpdu, si.dpdv, si.ns);
            // Get normal in world space
            vec3 texNormal = texture(normalTextures, vec3(si.uv, mat.normalTexId)).rgb;
            texNormal = texNormal * 2.0 - 1.0;
            ns = normalize(localToWorld * texNormal);
        }
        
        ns = EnsureValidReflection(si.ng, -ray.d, ns);
        si.ns = ns;

        // Build an Orthonormal basis (ONB)
        vec3 helper = abs(ns.z) > 0.999 ? vec3(0, 1, 0) : vec3(0, 0, 1);
        dpdu = normalize(cross(helper, ns));
        dpdv = cross(ns, dpdu);

        si.localToWorld = mat3(dpdu, dpdv, ns);
        si.worldToLocal = transpose(si.localToWorld);

        if (mat.alphaMode == 1) {
            // MASK
            if (mat.alpha < mat.alphaCutoff) {
                // Advance the ray and ignore the hit
                ray.o = si.p + ray.d * EPSILON;
                continue;
            }
        }
        if (mat.alphaMode == 2) {
            // BLEND
            if (Pcg3d(rng).x > mat.alpha) {
                // Advance the ray and ignore the hit
                ray.o = si.p + ray.d * EPSILON;
                continue;
            }
        }

        // Prevent 0 roughness which results in NaN in many functions
        mat.roughness = max(mat.roughness, 1e-2);
        si.mat = mat;
        
        // Add light contribution
        if (mat.hasEmission == 1) {
            if (misMode == 0) {
                if (isFirstHit) {
                    radiance += throughput * mat.emissive * mat.emissiveStrength;
                } else {
                    // Multiple Importance Sample (MIS)
                    // --------------------------------
                    float areaLightPdf = AreaLightPdf(si, ray, prevPoint);
                    float misWeight = PowerHeuristic(1, prevBsdfPdf, 1, areaLightPdf);
                    vec3 indirect = mat.emissive * mat.emissiveStrength * misWeight;
                    indirect = ClampLuminance(indirect, MAX_INDIRECT_LUMINANCE);
                    radiance += throughput * indirect;
                }
            } else if (misMode == 1) {
                radiance += throughput * mat.emissive * mat.emissiveStrength;
            }
        }
        
        if (misMode == 0) {
            vec3 direct = vec3(0.0);
            for (int i = 0; i < lights.length(); i++) {
                if (lights[i].type == 1) {
                    direct += SampleInfinitePunctualLight(si, ray, lights[i], rng);
                }
            }
            direct += SampleFinitePunctualLight(si, ray, rng);
            direct += SampleAreaLight(si, ray, rng);
            direct += SampleHdriLight(si, ray, rng);

            direct = ClampLuminance(direct, MAX_DIRECT_LUMINANCE);

            radiance += throughput * direct;
        }

        BsdfSample bsdfSample = SampleBsdf(rng, ray, si, bounceDepth);

        if (isFirstHit) {
            pathSample.baseCol = mat.baseCol;
            pathSample.normal = si.ns;
            // Subtract from 1 as depth color reduces with distance
            float depth = 1.0 - si.t * depthFactor / 2.0;
            pathSample.depth = clamp(depth, 0.0, 1.0);

            isFirstHit = false;

            if (debugMode == 1) { // Albedo
                pathSample.combined = pathSample.baseCol;
                break;
            } else if (debugMode == 2) { // Normal
                // Encode to range [0, 1]
                pathSample.combined = pathSample.normal * 0.5 + 0.5;
                break;
            } else if (debugMode == 3) { // Depth
                pathSample.combined = vec3(pathSample.depth);
                break;
            }
        }

        prevBsdfPdf = bsdfSample.pdf;
        prevPoint = si.p;

        bool didRefract = dot(bsdfSample.wi, si.ng) < 0.0;

        vec3 transmittance;
        BeerLambert(isInsideMedium, entryPoint, si, transmittance, didRefract);

        throughput *= transmittance;
        throughput *= bsdfSample.f;

        throughput = ClampLuminance(throughput, MAX_INDIRECT_LUMINANCE);

        ray.d = bsdfSample.wi;

        vec3 offsetDir = didRefract ? -si.ng : si.ng;
        ray.o = OffsetRayOrigin(si.p, offsetDir);

        // Russian Roulette
        // https://pbr-book.org/3ed-2018/Monte_Carlo_Integration/Russian_Roulette_and_Splitting

        if (i > 3) {
            // Termination probability
            float q = 1.0 - max(throughput.r, max(throughput.g, throughput.b));
            float Xi = Pcg3d(rng).x;

            if (Xi < q) {
                // Return radiance so far
                break;
            } else {
                throughput = throughput / (1.0 - q);
            }
        }
    }
    
    if (debugMode == 0) { // Off
        pathSample.combined = radiance;
    }

    return pathSample;
}

void main() {
    ivec2 pixelCoords = uOffset + ivec2(gl_GlobalInvocationID.xy);
    ivec2 dims = imageSize(combinedPass);

    // Only render pixels in frame
    if (pixelCoords.x >= dims.x || pixelCoords.y >= dims.y) return;

    uvec3 state = InitRngState(pixelCoords);
    
    float maxLuminance = 100.0;

    vec3 sampleCombined = vec3(0.0);
    vec3 sampleBaseColor = vec3(0.0);
    vec3 sampleNormal = vec3(0.0);
    float sampleDepth = 0.0;
    for (int i = 0; i < samplesPerPixel; i++) {
        // Get random vec3 (range [0, 1])
        // Convert to range [-0.5, 0.5]
        vec3 noise = Pcg3d(state) - 0.5;
        // Anti-aliasing sub-pixel jitter
        vec2 jitter = noise.xy * blur;

        // Map pixel to Normalized Device Coordinates (-1 to 1)
        vec2 uv = (vec2(pixelCoords) + jitter) / vec2(dims) * 2.0 - 1.0;

        // Adjust for aspect ratio
        uv.x *= aspectRatio;

        float tanHalfFov = tan(radians(Camera.fov) * 0.5);
        vec3 pinholeDir = normalize(Camera.front + (uv.x * Camera.right * tanHalfFov) + (uv.y * Camera.up * tanHalfFov));

        vec3 focusPoint = Camera.pos + pinholeDir * Camera.focusDist;

        vec2 rd = Camera.aperture * SampleUnitDisk(state);
        vec3 offset = Camera.right * rd.x + Camera.up * rd.y;

        Ray ray;
        ray.o = Camera.pos + offset;
        ray.d = normalize(focusPoint - ray.o);

        PathSample pathSample = PathTrace(ray, state);
        
        if (any(isnan(pathSample.combined)) || any(isinf(pathSample.combined))) {
            pathSample.combined = vec3(0.0);
        }
        
        sampleCombined += pathSample.combined;
        sampleBaseColor += pathSample.baseCol;
        sampleNormal += pathSample.normal;
        sampleDepth += pathSample.depth;
    }
    sampleCombined /= float(samplesPerPixel);
    sampleBaseColor /= float(samplesPerPixel);
    sampleNormal /= float(samplesPerPixel);
    sampleDepth /= float(samplesPerPixel);

    vec3 oldCombined = imageLoad(combinedPass, pixelCoords).rgb;
    vec3 oldBaseColor = imageLoad(baseColorPass, pixelCoords).rgb;
    vec3 oldNormal = imageLoad(normalPass, pixelCoords).rgb;
    float oldDepth = imageLoad(depthPass, pixelCoords).r;
    float weight = float(samplesPerPixel) / (float(totalSamples + samplesPerPixel));
    
    vec3 finalCombined;
    vec3 finalBaseCol;
    vec3 finalNormal;
    float finalDepth;
    if (totalSamples == 0) {
        // Ignore old color
        // ----------------
        finalCombined = sampleCombined;
        finalBaseCol = sampleBaseColor;
        finalNormal = sampleNormal;
        finalDepth = sampleDepth;
    } else {
        finalCombined = mix(oldCombined.rgb, sampleCombined, weight);
        finalBaseCol = mix(oldBaseColor.rgb, sampleBaseColor, weight);
        finalNormal = mix(oldNormal.rgb, sampleNormal, weight);
        finalDepth = mix(oldDepth.r, sampleDepth, weight);
    }
    
    imageStore(combinedPass, pixelCoords, vec4(finalCombined, 1.0));
    imageStore(baseColorPass, pixelCoords, vec4(finalBaseCol, 1.0));
    imageStore(normalPass, pixelCoords, vec4(finalNormal, 1.0));
    imageStore(depthPass, pixelCoords, vec4(vec3(finalDepth), 1.0));
}
