#version 460 core


layout(local_size_x=16, local_size_y=16) in;


#include "src/shaders/common.glsl"
#include "src/shaders/path_tracing/util.glsl"
#include "src/shaders/path_tracing/bsdf.glsl"
#include "src/shaders/path_tracing/intersect.glsl"
#include "src/shaders/path_tracing/light_env.glsl"
#include "src/shaders/path_tracing/light_punctual.glsl"
#include "src/shaders/path_tracing/light_area.glsl"
#include "src/shaders/path_tracing/volume.glsl"


// See 8.3 The Path Integrator
PathSample PathTrace(Ray ray, inout uvec3 rng) {
    SurfaceInteraction si;

    si.nodesVisited = 0;
    si.mat.ior = 1.0;

    vec3 throughput = vec3(1.0);

    vec3 diffuseDirect = vec3(0.0);
    vec3 specularDirect = vec3(0.0);
    vec3 diffuseIndirect = vec3(0.0);
    vec3 specularIndirect = vec3(0.0);

    // Entry point of a ray travelling through a medium
    vec3 entryPoint = vec3(0.0);
    bool isInsideMedium = false;

    // Used for acumulating the ray distance when it passes through an alpha material
    float tAccum = 0.0;

    PathSample pathSample;
    pathSample.baseCol = vec3(0.0);
    pathSample.normal = vec3(0.0);
    pathSample.depth = 0.0;
    pathSample.combined = vec3(0.0);

    float prevBsdfPdf = 0.0;
    int prevLobeType = 0; // Diffuse: 0, specular: 1, transmission: 2
    vec3 prevPoint = vec3(0.0);

    BounceDepth bounceDepth;
    bounceDepth.diffuse = 0;
    bounceDepth.specular = 0;
    bounceDepth.transmission = 0;

    for (int i = 0; i <= maxTotalBounces; i++) {
        if (bounceDepth.diffuse > maxDiffuseBounces || 
            bounceDepth.specular > maxSpecularBounces || 
            bounceDepth.transmission > maxTransmissionBounces) {
            break;
        }

        if (!Intersect(ray, si)) {
            /* Ray exited the scene */

            if (i == 0) {
                pathSample.depth = -1.0;
                pathSample.baseCol = vec3(1.0);
            }

            // See 7.3 HDRI Sampling
            vec3 envColor = SampleHdri(ray.d);

            if (misMode == 0) {
                if (i == 0) {
                    /* Add direct contribution */

                    vec3 contribution = throughput * envColor * hdriExposure;

                    diffuseDirect += contribution;
                } else {
                    /*
                     * Multiple importance sample (MIS)
                     * See 7.7 Multiple Importance Sampling
                     */

                    // See 7.3 HDRI Sampling
                    float lightPdf = HdriPdf(ray.d);
                    float misWeight = PowerHeuristic(1, prevBsdfPdf, 1, lightPdf);

                    if (i == 1) {
                        /* Add direct contribution */
                        
                        // See 2.3 Firefly Clamping
                        vec3 contribution = ClampLuminance(throughput * envColor * hdriExposure * misWeight, maxDirectLuminance);

                        if (prevLobeType != 0) { // Specular or transmission
                            specularDirect += contribution;
                        } else {
                            diffuseDirect += contribution;
                        }
                    } else {
                        /* Add indirect contribution */

                        // See 2.3 Firefly Clamping
                        vec3 contribution = ClampLuminance(throughput * envColor * hdriExposure * misWeight, maxIndirectLuminance);

                        if (prevLobeType != 0) { // Specular or transmission
                            specularDirect += contribution;
                        } else {
                            diffuseDirect += contribution;
                        }
                    }
                }
            } else if (misMode == 1) {
                /* No Multiple importance sample (only BSDF samples) */

                if (i == 0 || i == 1) {
                    /* Add direct contribution */

                    // See 2.3 Firefly Clamping
                    vec3 contribution = ClampLuminance(throughput * envColor * hdriExposure, maxDirectLuminance);
                    
                    if (prevLobeType != 0) { // Specular or transmission
                        specularDirect += contribution;
                    } else {
                        diffuseDirect += contribution;
                    }
                } else {
                    /* Add indirect contribution */

                    // See 2.3 Firefly Clamping
                    vec3 contribution = ClampLuminance(throughput * envColor * hdriExposure, maxIndirectLuminance);
                    
                    if (prevLobeType != 0) { // Specular or transmission
                        specularDirect += contribution;
                    } else {
                        diffuseDirect += contribution;
                    }
                }
            }

            break;
        }

        Triangle tri = triangles[si.triId];

        vec2 bary = si.bary;
        float u = bary.x;
        float v = bary.y;
        vec3 ng = si.ng;

        float w = 1.0 - u - v;
        vec2 texCoords = w * tri.v0.uv + u * tri.v1.uv + v * tri.v2.uv;

        vec3 ns = normalize(w * tri.v0.n + u * tri.v1.n + v * tri.v2.n);
        vec3 dpdu = normalize(w * tri.v0.dpdu + u * tri.v1.dpdu + v * tri.v2.dpdu);
        vec3 dpdv = normalize(w * tri.v0.dpdv + u * tri.v1.dpdv + v * tri.v2.dpdv);
        
        bool isBackFace = dot(ng, ray.d) > 0.0;

        if (isBackFace) {
            ng = -ng;
            ns = -ns;
            dpdu = -dpdu;
            dpdv = -dpdv;
        }

        Material mat = materials[tri.matId];

        if (isBackFace) {
            /*
             * The ray is exiting the object
             * travelling from the medium to the air.
             */

            si.eta_i = mat.ior;
            // Approximation for the IOR of air
            si.eta_t = 1.0;
        } else {
            /*
             * The ray is entering the object
             * travelling from air to the medium.
             */

            // Approximation for the IOR of air
            si.eta_i = 1.0;
            si.eta_t = mat.ior;
        }
        
        // See 2.4 Ray Utilities
        si.p = GetRayPoint(ray, si.t);
        si.ng = ng;
        si.ns = ns;
        si.dpdu = dpdu;
        si.dpdv = dpdv;
        si.uv = texCoords;
        si.isBackFace = isBackFace;
        si.area = tri.area;

        if (mat.hasBaseColTex == 1) {
            /* Sample base color texture */

            vec4 baseCol = texture(baseColorTextures, vec3(si.uv, mat.baseTexId));
            mat.baseCol = baseCol.rgb;
            mat.alpha = baseCol.w;
        }
        if (mat.hasEmissiveTex == 1) {
            /* Sample emissive texture */

            mat.emissive = texture(emissiveTextures, vec3(si.uv, mat.emissiveTexId)).rgb;
        }
        if (mat.hasMetalTex == 1) {
            /*
             * Sample metallic texture
             * Combine with the metallic factor because the final metallic
             * is factor * texture sample, not just the texture sample.
             * Using = instead of *= silently ignores the metallic factor
             * whenever a texture is present.
             */

            mat.metallic *= texture(metallicTextures, vec3(si.uv, mat.metalTexId)).r;
        }
        if (mat.hasRoughTex == 1) {
            /*
             * Sample roughness texture
             * The same rule as the metallic texture
             * applies to roughness: factor * texture sample.
             */

            mat.roughness *= texture(roughnessTextures, vec3(si.uv, mat.roughTexId)).r;
        }
        // https://learnopengl.com/Advanced-Lighting/Normal-Mapping
        if (mat.hasNormalTex == 1) {
            /* Sample normal map texture */

            mat3 localToWorld = mat3(si.dpdu, si.dpdv, si.ns);
            // Get normal in world space
            vec3 texNormal = texture(normalTextures, vec3(si.uv, mat.normalTexId)).rgb;
            texNormal = texNormal * 2.0 - 1.0;
            ns = normalize(localToWorld * texNormal);
        }
        
        // See 2.5 Ensuring Valid Reflections
        ns = EnsureValidReflection(si.ng, -ray.d, ns);
        si.ns = ns;

        // See 2.7 Orthonormal Basis
        ONB(ns, dpdu, dpdv);

        si.localToWorld = mat3(dpdu, dpdv, ns);
        si.worldToLocal = transpose(si.localToWorld);

        if (mat.alphaMode == 1) {
            /* MASK */

            if (mat.alpha < mat.alphaCutoff) {
                // Advance the ray and ignore the hit
                ray.o = si.p + ray.d * EPSILON;
                tAccum += si.t;
                // Decrement to effectly ignore the hit
                i--;
                continue;
            }
        }
        if (mat.alphaMode == 2) {
            /* BLEND */

            // See 2.2 The PCG Hash
            if (Pcg3d(rng).x > mat.alpha) {
                // Advance the ray and ignore the hit
                ray.o = si.p + ray.d * EPSILON;
                tAccum += si.t;
                // Decrement to effectly ignore the hit
                i--;
                continue;
            }
        }

        // Prevent 0 roughness which can result in NaN
        mat.roughness = max(mat.roughness, 3e-2);
        si.mat = mat;
        
        if (mat.hasEmission == 1) {
            if (misMode == 0) {
                /*
                 * Multiple importance sample (MIS)
                 * See 7.7 Multiple Importance Sampling
                 */

                if (i == 0) {
                    /* Add direct contribution */

                    // See 2.3 Firefly Clamping
                    vec3 contribution = ClampLuminance(throughput * mat.emissive * mat.emissiveStrength, maxDirectLuminance);

                    // Treat direct emission as diffuse for simplicity
                    diffuseDirect += contribution;
                } else {
                    /*
                     * Add indirect contribution
                     * Multiple importance sample (MIS)
                     */

                    // See 7.6 Area Light Sampling
                    float areaLightPdf = AreaLightPdf(si, ray, prevPoint);
                    float misWeight = PowerHeuristic(1, prevBsdfPdf, 1, areaLightPdf);
                    vec3 indirect = mat.emissive * mat.emissiveStrength * misWeight;

                    // See 2.3 Firefly Clamping
                    vec3 contribution = ClampLuminance(throughput * indirect, maxIndirectLuminance);

                    if (prevLobeType != 0) { // Specular or transmission
                        specularDirect += contribution;
                    } else {
                        diffuseDirect += contribution;
                    }
                }
            } else if (misMode == 1) {
                /*
                 * Multiple importance sample (MIS)
                 * (only BSDF samples)
                 */
                
                if (i == 0) {
                    /* Add direct contribution */

                    // See 2.3 Firefly Clamping
                    vec3 contribution = ClampLuminance(throughput * mat.emissive * mat.emissiveStrength, maxDirectLuminance);

                    // Treat direct emission as diffuse for simplicity
                    diffuseDirect += contribution;
                } else {
                    /* Add indirect contribution */

                    // See 2.3 Firefly Clamping
                    vec3 contribution = ClampLuminance(throughput * mat.emissive * mat.emissiveStrength, maxIndirectLuminance);

                    if (prevLobeType != 0) { // Specular or transmission
                        specularDirect += contribution;
                    } else {
                        diffuseDirect += contribution;
                    }
                }
            }
        }
        
        if (misMode == 0) {
            /*
             * Multiple importance sample (MIS)
             * See 7.7 Multiple Importance Sampling
             */

            /* Add direct contribution */

            BsdfSplit direct;
            direct.diffuse = vec3(0.0);
            direct.specular = vec3(0.0);

            for (int i = 0; i < lights.length(); i++) {
                if (lights[i].type == 1) {
                    // See 7.5 Punctual Lights
                    BsdfSplit s0 = SampleInfinitePunctualLight(si, ray, lights[i], rng);
                    direct.diffuse += s0.diffuse;
                    direct.specular += s0.specular;
                }
            }
            // See 7.5 Punctual Lights
            BsdfSplit s1 = SampleFinitePunctualLight(si, ray, rng);
            direct.diffuse += s1.diffuse;
            direct.specular += s1.specular;

            // See 7.6 Area Light Sampling
            BsdfSplit s2 = SampleAreaLight(si, ray, rng);
            direct.diffuse += s2.diffuse;
            direct.specular += s2.specular;

            // See 7.3 HDRI Sampling
            BsdfSplit s3 = SampleHdriLight(si, ray, rng);
            direct.diffuse += s3.diffuse;
            direct.specular += s3.specular;

            if (i == 0) {
                /* Add direct contribution */
                
                // See 2.3 Firefly Clamping
                direct.diffuse = ClampLuminance(direct.diffuse, maxDirectLuminance);
                direct.specular = ClampLuminance(direct.specular, maxDirectLuminance);

                diffuseDirect += throughput * direct.diffuse;
                specularDirect += throughput * direct.specular;
            } else {
                /* Add indirect contribution */

                // See 2.3 Firefly Clamping
                direct.diffuse = ClampLuminance(direct.diffuse, maxIndirectLuminance);
                direct.specular = ClampLuminance(direct.specular, maxIndirectLuminance);

                diffuseIndirect += throughput * direct.diffuse;
                specularIndirect += throughput * direct.specular;
            }
        }

        // See 5.11 BSDF Sampling
        BsdfSample bsdfSample = SampleBsdf(rng, ray, si, bounceDepth);

        if (i == 0) {
            /*
             * Debug passes
             * Add direct contribution
             */
            
            pathSample.baseCol = mat.baseCol;
            pathSample.normal = si.ns;
            pathSample.depth = tAccum + si.t;
            pathSample.metallic = mat.metallic;
            pathSample.roughness = mat.roughness;

            if (debugMode == 5) {
                /* Albedo */

                pathSample.combined = pathSample.baseCol;
                break;
            } else if (debugMode == 6) {
                /* Normal */

                // Encode to range [0, 1]
                pathSample.combined = pathSample.normal * 0.5 + 0.5;
                break;
            } else if (debugMode == 7) {
                /* Depth */

                pathSample.combined = vec3(pathSample.depth);
                break;
            } else if (debugMode == 8) {
                /* Metallic */

                pathSample.combined = vec3(pathSample.metallic);
                break;
            } else if (debugMode == 9) {
                /* Roughness */

                pathSample.combined = vec3(pathSample.roughness);
                break;
            } else if (debugMode == 11) {
                /*
                 * BVH depth
                 * See 4.4 Debug Visualization
                 */

                pathSample.combined = GetBvhDepthColor(si.nodesVisited, MAX_NODES_VISITED);
                break;
            }
        }

        prevBsdfPdf = bsdfSample.pdf;
        prevLobeType = bsdfSample.lobeType;
        prevPoint = si.p;

        bool didRefract = dot(bsdfSample.wi, si.ng) < 0.0;

        // See 6.2 Beer-Lambert Law
        vec3 transmittance;
        BeerLambert(isInsideMedium, entryPoint, si, transmittance, didRefract);

        /*
         * Throughput Accumulation
         * See 8.1 Overview
         */

        throughput *= transmittance;
        // See 2.3 Firefly Clamping
        throughput *= ClampLuminance(bsdfSample.f, maxBsdfLuminance);

        ray.d = bsdfSample.wi;

        vec3 offsetDir = didRefract ? -si.ng : si.ng;
        ray.o = OffsetRayOrigin(si.p, offsetDir);

        /*
         * Russian Roulette
         * See 8.2 Russian Roulette
         */
        
        if (i > 3) {
            // Termination probability
            float q = 1.0 - max(throughput.r, max(throughput.g, throughput.b));
            // See 2.2 The PCG Hash
            float Xi = Pcg3d(rng).x;

            if (Xi < q) {
                // Return radiance so far
                break;
            } else {
                throughput = throughput / (1.0 - q);
            }
        }
    }

    pathSample.diffuse = diffuseDirect + diffuseIndirect;
    pathSample.specular = specularDirect + specularIndirect;

    if (debugMode == 0) {
        /* Off (Combined) */

        pathSample.combined = pathSample.diffuse + pathSample.specular;
    } else if (debugMode == 1) {
        /* Diffuse */

        pathSample.combined = pathSample.diffuse;
    } else if (debugMode == 2) {
        /* Specular */

        pathSample.combined = pathSample.specular;
    } else if (debugMode == 3) {
        /* Direct */

        pathSample.combined = diffuseDirect + specularDirect;
    } else if (debugMode == 4) {
        /* Indirect */

        pathSample.combined = diffuseIndirect + specularIndirect;
    } else if (debugMode == 10) {
        /* Demodulated Diffuse */

        if (pathSample.depth < 0.0) {
            pathSample.combined = pathSample.diffuse + pathSample.specular;
        } else {
            vec3 safeAlbedo = max(pathSample.baseCol, vec3(EPSILON));
            pathSample.combined = (pathSample.diffuse + pathSample.specular) / safeAlbedo;
        }
    }

    return pathSample;
}

void main() {
    ivec2 pixelCoords = uOffset + ivec2(gl_GlobalInvocationID.xy);
    ivec2 dims = imageSize(combinedPass);

    // Only render pixels in frame
    if (pixelCoords.x >= dims.x || pixelCoords.y >= dims.y) return;

    // See 2.2 The PCG Hash
    uvec3 state = InitRngState(pixelCoords);
    
    vec3 sampleCombined = vec3(0.0);
    vec3 sampleDiffuse = vec3(0.0);
    vec3 sampleSpecular = vec3(0.0);
    vec3 sampleBaseColor = vec3(0.0);
    vec3 sampleNormal = vec3(0.0);
    float sampleDepth = 0.0;
    float sampleHitCount = 0.0;

    for (int i = 0; i < samplesPerPixel; i++) {
        // Get random vec3 (range [0, 1])
        // Convert to range [-0.5, 0.5]
        // See 2.2 The PCG Hash
        vec3 noise = Pcg3d(state) - 0.5;
        // Anti-aliasing sub-pixel jitter
        vec2 jitter = noise.xy * blur;

        // Map pixel to Normalized Device Coordinates (-1 to 1)
        vec2 uv = (vec2(pixelCoords) + jitter) / vec2(dims) * 2.0 - 1.0;

        // Adjust for aspect ratio
        uv.x *= aspectRatio;

        /* Pinhole camera direction */

        float tanHalfFov = tan(radians(Camera.fov) * 0.5);
        vec3 pinholeDir = normalize(Camera.front + (uv.x * Camera.right * tanHalfFov) + (uv.y * Camera.up * tanHalfFov));
        
        /* Depth of field (DOF) ray origin & direction offset */

        vec3 focusPoint = Camera.pos + pinholeDir * Camera.focusDist;
        vec2 rd = Camera.aperture * UniformSampleUnitDisk(state);
        vec3 offset = Camera.right * rd.x + Camera.up * rd.y;

        Ray ray;
        ray.o = Camera.pos + offset;
        ray.d = normalize(focusPoint - ray.o);

        PathSample pathSample = PathTrace(ray, state);
        
        if (any(isnan(pathSample.combined)) || any(isinf(pathSample.combined))) {
            /*
             * Remove any lingering NaN or Infs
             * to prevent permanent artifacts in the render.
             */
            
            pathSample.combined = vec3(0.0);
        } if (any(isnan(pathSample.diffuse)) || any(isinf(pathSample.diffuse))) {
            /*
             * Remove any lingering NaN or Infs
             * to prevent permanent artifacts in the render.
             */
            
            pathSample.diffuse = vec3(0.0);
        } if (any(isnan(pathSample.specular)) || any(isinf(pathSample.specular))) {
            /*
             * Remove any lingering NaN or Infs
             * to prevent permanent artifacts in the render.
             */
            
            pathSample.specular = vec3(0.0);
        }
        
        sampleCombined += pathSample.combined;
        sampleDiffuse += pathSample.diffuse;
        sampleSpecular += pathSample.specular;
        sampleBaseColor += pathSample.baseCol;
        sampleNormal += pathSample.normal;
        
        if (pathSample.depth >= 0.0) {
            sampleDepth += pathSample.depth;
            sampleHitCount += 1.0;
        }
    }

    sampleCombined /= float(samplesPerPixel);
    sampleDiffuse /= float(samplesPerPixel);
    sampleSpecular /= float(samplesPerPixel);
    sampleBaseColor /= float(samplesPerPixel);
    sampleNormal /= float(samplesPerPixel);
    float sampleHitFraction = sampleHitCount / float(samplesPerPixel);
    // Set the depth to be -1.0 if there were no hits so that the
    // CPU side can correctly normalize the image by ignoring depth < 0.0
    sampleDepth = sampleHitCount > 0.0 ? sampleDepth / sampleHitCount : -1.0;

    vec3 oldCombined = imageLoad(combinedPass, pixelCoords).rgb;
    vec3 oldDiffuse = imageLoad(diffusePass, pixelCoords).rgb;
    vec3 oldSpecular = imageLoad(specularPass, pixelCoords).rgb;
    vec3 oldBaseColor = imageLoad(baseColorPass, pixelCoords).rgb;
    vec3 oldNormal = imageLoad(normalPass, pixelCoords).rgb;
    vec2 oldDepth = imageLoad(depthPass, pixelCoords).rg;

    float weight = float(samplesPerPixel) / (float(totalSamples + samplesPerPixel));
    
    vec3 finalCombined;
    vec3 finalDiffuse;
    vec3 finalSpecular;
    vec3 finalBaseCol;
    vec3 finalNormal;
    float finalDepth;
    float finalHitFraction;

    if (totalSamples == 0) {
        /* Ignore old color */

        finalCombined = sampleCombined;
        finalDiffuse = sampleDiffuse;
        finalSpecular = sampleSpecular;
        finalBaseCol = sampleBaseColor;
        finalNormal = sampleNormal;
        finalDepth = sampleDepth;
        finalHitFraction = sampleHitFraction;
    } else {
        /* Progressive accumulation */

        finalCombined = mix(oldCombined.rgb, sampleCombined, weight);
        finalDiffuse = mix(oldDiffuse.rgb, sampleDiffuse, weight);
        finalSpecular = mix(oldSpecular.rgb, sampleSpecular, weight);
        finalBaseCol = mix(oldBaseColor.rgb, sampleBaseColor, weight);
        finalNormal = mix(oldNormal.rgb, sampleNormal, weight);
        finalHitFraction = mix(oldDepth.g, sampleHitFraction, weight);

        float oldHits = oldDepth.g * float(totalSamples);
        float newHits = oldHits + sampleHitCount;

        if (sampleHitCount > 0.0) {
            float hitWeight = sampleHitCount / newHits;
            finalDepth = mix(oldDepth.r, sampleDepth, hitWeight);
        } else {
            finalDepth = oldDepth.r;
        }
    }
    
    imageStore(combinedPass, pixelCoords, vec4(finalCombined, 1.0));
    imageStore(diffusePass, pixelCoords, vec4(finalDiffuse, 1.0));
    imageStore(specularPass, pixelCoords, vec4(finalSpecular, 1.0));
    imageStore(baseColorPass, pixelCoords, vec4(finalBaseCol, 1.0));
    imageStore(normalPass, pixelCoords, vec4(finalNormal, 1.0));
    imageStore(depthPass, pixelCoords, vec4(finalDepth, finalHitFraction, 0.0, 1.0));
}
