#version 460 core


layout(local_size_x=16, local_size_y=16) in;

layout(rgba32f, binding = 0) uniform image2D combinedPass;
layout(rgba32f, binding = 1) uniform image2D baseColorPass;
layout(rgba32f, binding = 2) uniform image2D normalPass;
layout(rgba32f, binding = 3) uniform image2D depthPass;

uniform float aspectRatio;
// Top left corner of the current tile
uniform ivec2 uOffset;

layout(std430, binding = 0) buffer CameraBuffer {
    vec3 pos;
    float aperture;
    vec3 front;
    float focusDist;
    vec3 up;
    int autoFocus;
    vec3 right;
    float fov;
} Camera;

struct Vertex {
    vec3 pos;
    float pad1;
    vec2 uv;
    vec2 pad2;
    vec3 normal;
    float pad3;
    vec3 tangent;
    float pad4;
    vec3 bitangent;
    float pad5;
};

struct Material {
    // Basic material
    vec3 baseCol;
    float alpha;
    vec3 emissive;
    float metallic;
    float roughness;
    float ao;
    // Settings
    int alphaMode; // 0=OPAQUE, 1=MASK, or 2=BLEND
    float alphaCutoff;
    int doubleSided;
    // Flags
    int hasEmission;
    int hasBaseColTex;
    int hasEmissiveTex;
    int hasRoughTex;
    int hasMetalTex;
    int hasNormalTex;
    int hasOcclTex;
    // Texture IDs
    int baseTexId;
    int emissiveTexId;
    int roughTexId;
    int metalTexId;
    int normalTexId;
    int occlTexId;
    // glTF extensions
    float emissiveStrength;
    float transmission;
    float ior;
    float pad1;
    float pad2;
    float pad3;
};

struct Triangle {
    Vertex v0, v1, v2;
    int matId;
    float area; // -1 if not emissive
    float pad1, pad2;
};

struct BVHNode {
    vec3 aabbMin;
    int leftChildIdx;
    vec3 aabbMax;
    int rightChildIdx;
    int firstTriIdx;
    int triCount;
    int isLeaf;
    float pad1;
};

struct Light {
    vec3 col;
    int type; // Point: 0, directional: 1, spot: 2
    vec3 pos;
    float intensity;
    vec3 dir;
    float range;
    int isSpot;
    float innerConeAngle;
    float outerConeAngle;
    float pad1;
};

struct EmissiveTriangle {
    int triIdx;
};

layout(std430, binding = 1) buffer TriangleBuffer {
    Triangle triangles[];
};

layout(std430, binding = 2) buffer MaterialBuffer {
    Material materials[];
};

layout (std430, binding = 3) buffer LightBuffer {
    Light lights[];
};

layout(std430, binding = 4) buffer BVHNodesBuffer {
    BVHNode BVHNodes[];
};

layout(std430, binding = 5) buffer TriIndicesBuffer {
    int triIndices[];
};

layout(std430, binding = 6) buffer EmissiveTrianglesBuffer {
    EmissiveTriangle emissiveTriangles[];
};

layout(binding = 0) uniform sampler2DArray baseColorTextures;
layout(binding = 1) uniform sampler2DArray emissiveTextures;
layout(binding = 2) uniform sampler2DArray roughnessTextures;
layout(binding = 3) uniform sampler2DArray metallicTextures;
layout(binding = 4) uniform sampler2DArray normalTextures;
layout(binding = 5) uniform sampler2DArray occlusionTextures;

layout(binding = 6) uniform sampler2D hdri;
layout(binding = 7) uniform sampler2D hdriRowCDF;
layout(binding = 8) uniform sampler2D hdriColCDF;

struct Ray {
    vec3 orig;
    vec3 dir;
    vec3 col;
};

struct HitRecord {
    vec3 point;
    vec3 geoNormal;
    vec3 normal;
    vec3 tangent;
    vec3 bitangent;
    mat3 TBN;
    mat3 InvTBN;
    float baryU;
    float baryV;
    vec2 uv;
    Material mat;
    float eta; // IOR ratio
    float t;
    int triIdx;
    bool backFace;
    // Only used for emissive triangles
    float triArea;
};

struct ShadowRecord {
    float t;
    bool backFace;
};

#define EPSILON 1e-4
#define INF 1e20
#define PI 3.14159265359

uniform int samplesPerPixel;
uniform int totalSamples;
uniform int maxBounces;
uniform float blur;
uniform float hdriExposure;
uniform float depthFactor;

// PCG 3d hash randomization
// http://www.jcgt.org/published/0009/03/02/
vec3 PCG3d(inout uvec3 v) {
    v = v * 1664525u + 1013904223u;
    v.x += v.y*v.z; v.y += v.z*v.x; v.z += v.x*v.y;
    v ^= v >> 16u;
    v.x += v.y*v.z; v.y += v.z*v.x; v.z += v.x*v.y;
    // Divide by 2^32 (uint32 limit) to convert to range [0, 1]
    return vec3(v) / 4294967295.0;
}

vec3 GetRayPoint(Ray ray, float t) {
    return ray.orig + t * ray.dir;
}

// https://pema.dev/obsidian/math/light-transport/cosine-weighted-sampling.html
vec3 CosineSampleHemisphere(inout uvec3 v, vec3 normal, HitRecord rec) {
    vec3 r = PCG3d(v);
    float r1 = r.x;
    float r2 = r.y;

    float theta = acos(sqrt(r1));
    float phi = 2.0 * PI * r2;
    
    // Sample in local space
    vec3 dir = vec3(
        sin(theta) * cos(phi),
        sin(theta) * sin(phi),
        cos(theta)
    );

    // Transform to world space
    return normalize(rec.TBN * dir);
}

// https://learnopengl.com/PBR/Theory
float DistributionGGX(vec3 N, vec3 H, float a) {
    float a2     = a * a;
    float NdotH  = max(dot(N, H), 0.0);
    float NdotH2 = NdotH * NdotH;
	
    float nom    = a2;
    float denom  = (NdotH2 * (a2 - 1.0) + 1.0);
    denom        = PI * denom * denom;
	
    return nom / max(denom, 1e-10);
}

// https://learnopengl.com/PBR/Theory
float GeometrySchlickGGX(float NdotV, float k) {
    float nom   = NdotV;
    float denom = NdotV * (1.0 - k) + k;
	
    return nom / denom;
}

// https://learnopengl.com/PBR/Theory
float GeometrySmith(vec3 N, vec3 V, vec3 L, float k) {
    float NdotV = max(dot(N, V), 0.0);
    float NdotL = max(dot(N, L), 0.0);
    float ggx1 = GeometrySchlickGGX(NdotV, k);
    float ggx2 = GeometrySchlickGGX(NdotL, k);
	
    return ggx1 * ggx2;
}

// https://schuttejoe.github.io/post/ggximportancesamplingpart2/
float SmithGGXMasking(vec3 L, vec3 V, vec3 N, float a2) {
    float dotNL = abs(dot(N, L));
    float dotNV = abs(dot(N, V));
    float denomC = sqrt(a2 + (1.0 - a2) * dotNV * dotNV) + dotNV;

    return 2.0 * dotNV / denomC;
}

// https://schuttejoe.github.io/post/ggximportancesamplingpart2/
float SmithGGXMaskingShadowing(vec3 L, vec3 V, vec3 N, float a2) {
    float dotNL = abs(dot(N, L));
    float dotNV = abs(dot(N, V));

    float denomA = dotNV * sqrt(a2 + (1.0 - a2) * dotNL * dotNL);
    float denomB = dotNL * sqrt(a2 + (1.0 - a2) * dotNV * dotNV);

    return 2.0 * dotNL * dotNV / (denomA + denomB);
}

// https://learnopengl.com/PBR/Theory
vec3 FresnelSchlick(float cosTheta, vec3 F0) {
    return F0 + (1.0 - F0) * pow(1.0 - cosTheta, 5.0);
}

// https://schuttejoe.github.io/post/ggximportancesamplingpart2/
vec3 ImportanceSampleGGXVNDF(vec2 Xi, vec3 V, float roughness) {
    // Stretch the view vector as if roughness = 1
    vec3 v = normalize(vec3(
        V.x * roughness,
        V.y * roughness,
        V.z
    ));

    // Build an orthonormal basis (ONB)
    vec3 helper = abs(v.z) > 0.999 ? vec3(1.0, 0.0, 0.0) : vec3(0.0, 0.0, 1.0);
    vec3 t1 = normalize(cross(helper, v));
    vec3 t2 = cross(v, t1);

    // Choose a point on a disk with each half of the disk weighted
    // proportionally to its projection onto direction v
    float a = 1.0 / (1.0 + v.z);
    float r = sqrt(Xi.x);
    float phi = (Xi.y < a) ? (Xi.y / a) * PI : PI + (Xi.y - a) / (1.0 - a) * PI;
    float p1 = r * cos(phi);
    float p2 = r * sin(phi) * ((Xi.y < a) ? 1.0 : v.z);

    // Calculate the normal in stretched tangent space
    vec3 n = p1 * t1 + p2 * t2 + sqrt(max(0.0, 1.0 - p1 * p1 - p2 * p2)) * v;

    // Unstretch and normalize the normal
    return normalize(vec3(
        roughness * n.x,
        roughness * n.y,
        max(0.0, n.z)
    ));
}

// Beer-Lambert law: light attenuates exponentially with distance traveled through a medium
// https://www.pbr-book.org/3ed-2018/Volume_Scattering/Volume_Scattering_Processes
void BeerLambert(inout bool insideMedium, inout vec3 entryPoint, HitRecord rec, out vec3 transmittance, bool didRefract) {
    transmittance = vec3(1.0);

    bool isTransmission = rec.mat.transmission > 0.0;
    bool isEntering = !rec.backFace;
    bool isExiting = rec.backFace;

    // Only apply when the material is transmissive and the ray is exiting the medium
    if (isTransmission) {
        if (isEntering && !insideMedium) {
            entryPoint = rec.point;
            insideMedium = true;
        } else if (isExiting && didRefract && insideMedium) {
            float distTravelled = length(rec.point - entryPoint);
            vec3 absorption = -log(rec.mat.baseCol);
            transmittance = exp(-absorption * distTravelled);

            insideMedium = false;
        }
    }
}

float GGXVNDF_PDF(vec3 N, vec3 V, vec3 L, float a) {
    float NdotV = abs(dot(N, V));
    vec3 H = normalize(V + L);
    float a2 = a * a;

    float D = DistributionGGX(N, H, a);
    float G1 = SmithGGXMasking(L, V, N, a2);

    return (D * G1) / (4.0 * NdotV);
}

float CosineSamplePDF(vec3 N, vec3 L) {
    float NdotL = max(dot(N, L), 0.0);
    return NdotL / PI;
}

// https://www.graphics.cornell.edu/~bjw/microfacetbsdf.pdf
float BTDF_PDF(vec3 N, vec3 V, vec3 L, float a, float eta) {
    float NdotV = abs(dot(N, V));
    float a2 = a * a;

    vec3 H = normalize(V + eta * L);
    if (dot(N, H) < 0.0) H = -H;

    float D = DistributionGGX(N, H, a);
    float G1 = SmithGGXMasking(L, V, N, a2);

    float VdotH = dot(V, H);
    float LdotH = dot(L, H);

    float denom = VdotH + eta * LdotH;
    float dwh_dwi = abs((eta * eta * LdotH) / max(denom * denom, 0.0001));
    return D * G1 * abs(VdotH) / max(NdotV, 0.0001) * dwh_dwi;
}

float BSDF_PDF(vec3 L, Ray ray, HitRecord rec) {
    Material mat = rec.mat;
    vec3 N = rec.normal;
    vec3 V = -ray.dir;

    float NdotV = abs(dot(N, V));

    vec3 F0 = vec3(0.04);
    F0 = mix(F0, mat.baseCol, mat.metallic);
    
    vec3 F_approx = FresnelSchlick(NdotV, F0);

    // AI method: average the Fresnel approximation for a single float probability
    float weight = (F_approx.r + F_approx.g + F_approx.b) / 3.0;
    
    float specularChance = clamp(weight, 0.05, 0.95);
    float refractChance = mat.transmission * (1.0 - specularChance);
    // Fully metal objects cannot refract
    refractChance *= (1.0 - mat.metallic);
    float diffuseChance = 1.0 - specularChance - refractChance;

    float NdotL = dot(N, L);

    float a = mat.roughness * mat.roughness;

    if (NdotL > 0.0) {
        float specularPdf = GGXVNDF_PDF(N, V, L, a) * specularChance;
        float diffusePdf = CosineSamplePDF(N, L) * diffuseChance;

        return specularPdf + diffusePdf;
    } else {
        return BTDF_PDF(N, V, L, a, rec.eta) * refractChance;
    }
}

float LightPDF(HitRecord rec, Ray ray, vec3 prevPoint) {
    int numEmissive = emissiveTriangles.length();

    Triangle tri = triangles[rec.triIdx];
    vec3 L = normalize(rec.point - prevPoint);
    float dist = length(rec.point - prevPoint);

    // Check if ray hit light's backface
    float cosLight = dot(rec.normal, -L);
    if (cosLight <= 0.0) {
        return 0.0;
    }

    float pdfTri = 1.0 / float(numEmissive);
    float pdfPoint = (dist * dist) / (cosLight * rec.triArea);
    float pdf = pdfTri * pdfPoint;
    return pdf;
}

// https://learnopengl.com/PBR/Theory
// https://schuttejoe.github.io/post/ggximportancesamplingpart1/
vec3 SampleBSDF(inout uvec3 v, Ray ray, HitRecord rec, out vec3 bounceDir, out float bsdfPdf) {
    Material mat = rec.mat;

    bool enteringMedium = !rec.backFace;

    vec3 N = rec.normal;
    vec3 geoN = rec.geoNormal;
    vec3 V = -ray.dir;

    vec3 Xi = PCG3d(v);

    float NdotV = abs(dot(N, V));

    vec3 F0 = vec3(0.04);
    F0 = mix(F0, mat.baseCol, mat.metallic);
    
    vec3 F_approx = FresnelSchlick(NdotV, F0);

    // AI method: average the Fresnel approximation for a single float probability
    float weight = (F_approx.r + F_approx.g + F_approx.b) / 3.0;
    
    float specularChance = clamp(weight, 0.05, 0.95);
    float refractChance = mat.transmission * (1.0 - specularChance);
    // Fully metal objects cannot refract
    refractChance *= (1.0 - mat.metallic);
    float diffuseChance = 1.0 - specularChance - refractChance;

    if (Xi.z < specularChance) {
        // Specular lobe

        float a = mat.roughness * mat.roughness;
        float a2 = a * a;

        // Convert V to tangent space for the GGX VNDF importance sample
        vec3 V_Tangent = rec.InvTBN * V;

        vec3 H_Tangent = ImportanceSampleGGXVNDF(Xi.xy, V_Tangent, a);

        // Transform H back to world space
        vec3 H = normalize(rec.TBN * H_Tangent);
        vec3 L = reflect(-V, H);
        bounceDir = L;

        // Below the surface
        if (dot(N, L) <= 0.0) {
            bsdfPdf = 0.0;
            return vec3(0.0);
        }

        float LdotH = dot(L, H);
        vec3 F = FresnelSchlick(LdotH, F0);

        float G1 = SmithGGXMasking(L, V, N, a2);
        float G2 = SmithGGXMaskingShadowing(L, V, N, a2);

        vec3 specular = F * (G2 / G1);

        bsdfPdf = BSDF_PDF(bounceDir, ray, rec);

        return specular / specularChance;
    } else {
        // Transmission/Diffuse lobe

        if (Xi.z < specularChance + refractChance) {
            // Transmission lobe

            float a = mat.roughness * mat.roughness;
            float a2 = a * a;

            // Convert V to tangent space for the GGX VNDF importance sample
            vec3 V_Tangent = rec.InvTBN * V;

            vec3 H_Tangent = ImportanceSampleGGXVNDF(Xi.xy, V_Tangent, a);

            // Transform H back to world space
            vec3 H = normalize(rec.TBN * H_Tangent);

            vec3 L = refract(ray.dir, H, rec.eta);

            // Total internal reflection (TIR)
            // GLSL refract function returns vec3(0.0) on TIR
            if (L == vec3(0.0)) {
                bounceDir = reflect(ray.dir, H);
                L = bounceDir;

                vec3 F = vec3(1.0);
                float G1 = SmithGGXMasking(L, V, N, a2);
                float G2 = SmithGGXMaskingShadowing(L, V, N, a2);

                vec3 specular = F * (G2 / G1);

                bsdfPdf = BSDF_PDF(bounceDir, ray, rec);

                return specular / refractChance;
            } else {
                bounceDir = L;
            }

            bsdfPdf = BSDF_PDF(bounceDir, ray, rec);

            return mat.baseCol / refractChance;
        } else {
            // Diffuse lobe

            vec3 L = CosineSampleHemisphere(v, N, rec);
            bounceDir = L;

            // Below surface
            if (dot(N, bounceDir) <= 0.0) {
                bsdfPdf = 0.0;
                return vec3(0.0);
            }

            vec3 H = normalize(V + L);

            float VdotH = abs(dot(V, H));

            vec3 F = FresnelSchlick(VdotH, F0);

            vec3 kS = F;
            vec3 kD = vec3(1.0) - kS;
            kD *= 1.0 - mat.metallic;
            kD *= 1.0 - mat.transmission;

            vec3 diffuse = kD * mat.baseCol;

            bsdfPdf = BSDF_PDF(bounceDir, ray, rec);

            return diffuse / diffuseChance;
        }
    }
}

// https://pbr-book.org/3ed-2018/Monte_Carlo_Integration/Importance_Sampling#MultipleImportanceSampling
float PowerHeuristic(int nf, float fPdf, int ng, float gPdf) {
    float f = float(nf) * fPdf;
    float g = float(ng) * gPdf;
    return (f * f) / (f * f + g * g);
}

// https://learnopengl.com/PBR/Theory
vec3 EvaluateBRDF(vec3 L, Ray ray, HitRecord rec) {
    Material mat = rec.mat;

    vec3 N = rec.normal;
    vec3 V = -ray.dir;

    vec3 F0 = vec3(0.04);
    F0 = mix(F0, mat.baseCol, mat.metallic);

    vec3 H = normalize(V + L);

    float a = mat.roughness * mat.roughness;
    float a2 = a * a;

    vec3 F = FresnelSchlick(max(dot(H, V), 0.0), F0);
    float D = DistributionGGX(N, H, a);
    float G = SmithGGXMaskingShadowing(L, V, N, a2);

    vec3 kS = F;
    vec3 kD = vec3(1.0) - kS;
    kD *= 1.0 - mat.metallic;
    kD *= 1.0 - mat.transmission;

    float NdotV = max(dot(N, V), 0.0);
    float NdotL = max(dot(N, L), 0.0);

    vec3 specular = (D * G * F) / max(4.0 * NdotV * NdotL, 0.0001);
    vec3 diffuse = kD * mat.baseCol / PI;

    vec3 brdf = (diffuse + specular) * NdotL;

    return brdf;
}

// https://www.graphics.cornell.edu/~bjw/microfacetbsdf.pdf
vec3 EvaluateBTDF(vec3 L, Ray ray, HitRecord rec) {
    Material mat = rec.mat;
    vec3 N = rec.normal;
    vec3 V = -ray.dir;
    float eta = rec.eta;

    float a = mat.roughness * mat.roughness;
    float a2 = a * a;

    vec3 H = normalize(V + eta * L);
    if (dot(N, H) < 0.0) H = -H;

    float NdotV = abs(dot(N, V));
    float NdotL = abs(dot(N, L));
    float VdotH = dot(V, H);
    float LdotH = dot(L, H);

    vec3 F0 = vec3(0.04);
    F0 = mix(F0, mat.baseCol, mat.metallic);
    vec3 F = FresnelSchlick(abs(VdotH), F0);

    float D = DistributionGGX(N, H, a);
    float G = SmithGGXMaskingShadowing(L, V, N, a2);

    float denom = VdotH + eta * LdotH;
    denom = max(denom * denom, 0.0001);

    float jacobian = abs(VdotH * LdotH) / max(NdotV * NdotL, 0.0001);

    vec3 btdf = (vec3(1.0) - F) * D * G * jacobian / denom;

    return btdf;
}

vec3 EvaluateBSDF(vec3 L, Ray ray, HitRecord rec) {
    vec3 N = rec.normal;
    float NdotL = dot(N, L);
    if (NdotL > 0.0) {
        return EvaluateBRDF(L, ray, rec);
    } else {
        return EvaluateBTDF(L, ray, rec);
    }
}

// Möller-Trumbore ray-triangle intersection algorithm
// https://www.scratchapixel.com/lessons/3d-basic-rendering/ray-tracing-rendering-a-triangle/moller-trumbore-ray-triangle-intersection.html
bool RayTriangleIntersect(Ray ray, Triangle tri, int triIdx, float closestSoFar, inout HitRecord rec) {
    vec3 e1 = tri.v1.pos - tri.v0.pos;
    vec3 e2 = tri.v2.pos - tri.v0.pos;
    vec3 pvec = cross(ray.dir, e2);
    float det = dot(e1, pvec);

    // If det is close to 0, ray is parallel to the triangle
    if (abs(det) < 1e-7) return false;

    float invDet = 1.0 / det;

    vec3 tvec = ray.orig - tri.v0.pos;
    float u = dot(tvec, pvec) * invDet;
    if (u < 0.0 || u > 1.0) return false;

    vec3 qvec = cross(tvec, e1);
    float v = dot(ray.dir, qvec) * invDet;
    if (v < 0.0 || u + v > 1.0) return false;
    
    float t = dot(e2, qvec) * invDet;
    // Check if the hit distance is positive and closer than current closest triangle
    if (t < EPSILON || t >= closestSoFar) return false;

    rec.baryU = u;
    rec.baryV = v;
    rec.t = t;
    rec.triIdx = triIdx;
    return true;
}

// Möller-Trumbore ray-triangle intersection algorithm
// https://www.scratchapixel.com/lessons/3d-basic-rendering/ray-tracing-rendering-a-triangle/moller-trumbore-ray-triangle-intersection.html
bool ShadowRayTriangleIntersect(inout uvec3 v, inout Ray ray, Triangle tri, int triIdx, float closestSoFar, inout ShadowRecord rec) {
    vec3 e1 = tri.v1.pos - tri.v0.pos;
    vec3 e2 = tri.v2.pos - tri.v0.pos;
    vec3 pvec = cross(ray.dir, e2);
    float det = dot(e1, pvec);

    // If det is close to 0, ray is parallel to the triangle
    if (abs(det) < 1e-7) return false;

    float invDet = 1.0 / det;

    vec3 tvec = ray.orig - tri.v0.pos;
    float u = dot(tvec, pvec) * invDet;
    if (u < 0.0 || u > 1.0) return false;

    vec3 qvec = cross(tvec, e1);
    float vv = dot(ray.dir, qvec) * invDet;
    if (vv < 0.0 || u + vv > 1.0) return false;
    
    float t = dot(e2, qvec) * invDet;
    // Check if the hit distance is positive and closer than current closest triangle
    if (t < EPSILON || t >= closestSoFar) return false;

    float w = 1.0 - u - vv;
    vec2 texCoords = w * tri.v0.uv + u * tri.v1.uv + vv * tri.v2.uv;

    Material mat = materials[tri.matId];

    if (mat.alphaMode != 0) {
        if (mat.hasBaseColTex == 1) {
            vec4 baseCol = texture(baseColorTextures, vec3(vec2(u, v), mat.baseTexId));
            mat.alpha = baseCol.w;
        }

        vec3 point = GetRayPoint(ray, t);

        if (mat.alphaMode == 1) {
            // MASK
            if (mat.alpha < mat.alphaCutoff) {
                // Advance the ray and ignore the hit
                ray.orig = point + ray.dir * EPSILON;
                return false;
            }
        }
        float blendRand = PCG3d(v).x;
        if (mat.alphaMode == 2) {
            // BLEND
            if (PCG3d(v).x > mat.alpha) {
                // Advance the ray and ignore the hit
                ray.orig = point + ray.dir * EPSILON;
                return false;
            }
        }
    }

    rec.t = t;
    return true;
}

bool AABBIntersect(Ray ray, vec3 invRayDir, BVHNode node, float closestSoFar) {
    vec3 t0 = (node.aabbMin - ray.orig) * invRayDir;
    vec3 t1 = (node.aabbMax - ray.orig) * invRayDir;
    
    vec3 tMin = min(t0, t1);
    vec3 tMaxAxis = max(t0, t1);

    float tNear = max(max(tMin.x, tMin.y), tMin.z);
    float tFar  = min(min(tMaxAxis.x, tMaxAxis.y), tMaxAxis.z);
    
    return tNear <= tFar && tFar > 0.0 && tNear < closestSoFar;
}

// https://jacco.ompf2.com/2022/04/18/how-to-build-a-bvh-part-2-faster-rays/
bool Hit(Ray ray, inout HitRecord rec) {
    HitRecord tempRec = rec;
    bool hitAnything = false;
    float closestSoFar = INF;

    int nodeStack[64];
    int stackIdx = 0;
    // Push root node index onto the stack
    nodeStack[stackIdx++] = 0;

    vec3 invRayDir = 1.0 / ray.dir;

    while (stackIdx > 0) {
        // Pop the latest node index off
        int currIdx = nodeStack[--stackIdx];
        BVHNode currNode = BVHNodes[currIdx];

        if (AABBIntersect(ray, invRayDir, currNode, closestSoFar)) {
            if (currNode.isLeaf == 1) {
                for (int i = 0; i < currNode.triCount; i++) {
                    int triIndex = triIndices[currNode.firstTriIdx + i];
                    Triangle tri = triangles[triIndex];
                    if (RayTriangleIntersect(ray, tri, triIndex, closestSoFar, tempRec)) {
                        hitAnything = true;
                        closestSoFar = tempRec.t;
                        rec = tempRec;
                    }
                }
            } else {
                // Push children onto the stack if there are children
                
                if (currNode.leftChildIdx != -1) {
                    nodeStack[stackIdx++] = currNode.leftChildIdx;
                }
                if (currNode.rightChildIdx != -1) {
                    nodeStack[stackIdx++] = currNode.rightChildIdx;
                }
            }
        }
    }

    return hitAnything;
}

bool TestVisibility(inout uvec3 v, Ray ray, inout ShadowRecord rec) {
    ShadowRecord tempRec = rec;
    bool occluded = false;
    float closestSoFar = INF;

    int nodeStack[64];
    int stackIdx = 0;
    // Push root node index onto the stack
    nodeStack[stackIdx++] = 0;

    vec3 invRayDir = 1.0 / ray.dir;

    while (stackIdx > 0) {
        // Pop the latest node index off
        int currIdx = nodeStack[--stackIdx];
        BVHNode currNode = BVHNodes[currIdx];

        if (AABBIntersect(ray, invRayDir, currNode, closestSoFar)) {
            if (currNode.isLeaf == 1) {
                for (int i = 0; i < currNode.triCount; i++) {
                    int triIndex = triIndices[currNode.firstTriIdx + i];
                    Triangle tri = triangles[triIndex];
                    if (ShadowRayTriangleIntersect(v, ray, tri, triIndex, closestSoFar, tempRec)) {
                        occluded = true;
                        closestSoFar = tempRec.t;
                        rec = tempRec;
                    }
                }
            } else {
                // Push children onto the stack if there are children
                
                if (currNode.leftChildIdx != -1) {
                    nodeStack[stackIdx++] = currNode.leftChildIdx;
                }
                if (currNode.rightChildIdx != -1) {
                    nodeStack[stackIdx++] = currNode.rightChildIdx;
                }
            }
        }
    }

    return occluded;
}

// https://pbr-book.org/3ed-2018/Light_Transport_I_Surface_Reflection/Sampling_Light_Sources#InfiniteAreaLights
int SampleRowCDF(float xi, int height, out float rowHigh, out float rowLow, out float rowPdf ) {
    // Binary search to find the correct row
    int lo = 0, hi = height - 1;
    while (lo < hi) {
        int mid = (hi + lo) / 2;
        float val = texelFetch(hdriRowCDF, ivec2(0, mid), 0).r;
        if (val < xi) {
            lo = mid + 1;
        } else {
            hi = mid;
        }
    }
    // Use lo as the chosen row index
    rowHigh = texelFetch(hdriRowCDF, ivec2(0, lo), 0).r;
    rowLow = lo > 0 ? texelFetch(hdriRowCDF, ivec2(0, lo - 1), 0).r : 0.0;
    rowPdf = max(rowHigh - rowLow, 1e-8);
    return lo;
}

// https://pbr-book.org/3ed-2018/Light_Transport_I_Surface_Reflection/Sampling_Light_Sources#InfiniteAreaLights
int SampleColCDF(float xi, int row, int width, out float colHigh, out float colLow, out float colPdf) {
    // Binary search to find the correct column
    int lo = 0, hi = width - 1;
    while (lo < hi) {
        int mid = (hi + lo) / 2;
        float val = texelFetch(hdriColCDF, ivec2(mid, row), 0).r;
        if (val < xi) {
            lo = mid + 1;
        } else {
            hi = mid;
        }
    }
    colHigh = texelFetch(hdriColCDF, ivec2(lo, row), 0).r;
    colLow = lo > 0 ? texelFetch(hdriColCDF, ivec2(lo - 1, row), 0).r : 0.0;
    colPdf = max(colHigh - colLow, 1e-8);
    return lo;
}

vec3 SampleHDRI(vec3 dir) {
    // Convert to spherical coordinates
    float phi = atan(dir.z, dir.x);
    float theta = acos(dir.y);
    // Convert to uv coordinates
    vec2 uv = vec2(phi / (2.0 * PI) + 0.5, theta / PI);
    return texture(hdri, uv).rgb;
}

// https://pbr-book.org/3ed-2018/Light_Transport_I_Surface_Reflection/Sampling_Light_Sources#InfiniteAreaLights
vec3 DirectSampleHDRI(inout uvec3 v, out vec3 dir, out float HDRIPdf) {
    ivec2 size = textureSize(hdri, 0);
    int width = size.x, height = size.y;

    vec3 Xi = PCG3d(v);

    float rowHigh, rowLow, rowPdf;
    int row = SampleRowCDF(Xi.x, height, rowHigh, rowLow, rowPdf);
    float colHigh, colLow, colPdf;
    int col = SampleColCDF(Xi.y, row, width, colHigh, colLow, colPdf);

    // Anti-aliasing sub-pixel jitter
    float dv = (Xi.x - rowLow) / rowPdf;
    float du = (Xi.y - colLow) / colPdf;

    // Sampled continuous point in ranges [0, 1)
    float u = (float(col) + du) / float(width);
    float vv = (float(row) + dv) / float(height);

    float theta = vv * PI;
    float phi = (u - 0.5) * 2.0 * PI;

    dir = normalize(vec3(
        sin(theta) * cos(phi),
        cos(theta),
        sin(theta) * sin(phi)
    ));

    float mapPdf = rowPdf * colPdf * float(width) * float(height);
    float sinTheta = sin(theta);
    HDRIPdf = sinTheta > 0.0 ?  mapPdf / (2.0 * PI * PI * sinTheta) : 0.0;

    return texture(hdri, vec2(u, vv)).rgb;
}

vec3 SampleHDRILight(HitRecord rec, Ray ray, inout uvec3 v) {
    vec3 L;
    float lightPdf;
    vec3 Li = DirectSampleHDRI(v, L, lightPdf);
    if (lightPdf <= 0.0) return vec3(0.0);

    vec3 N = rec.normal;

    float NdotL = dot(N, L);
    
    if (rec.mat.transmission == 0.0 && NdotL <= 0.0) {
        return vec3(0.0);
    }

    // Shadow ray
    Ray shadowRay;
    shadowRay.orig = rec.point + rec.geoNormal * EPSILON;
    shadowRay.dir = L;

    ShadowRecord shadowRec;
    bool occluded = TestVisibility(v, shadowRay, shadowRec);
    if (occluded) {
        return vec3(0.0); // Occluded
    }

    vec3 f = EvaluateBSDF(L, ray, rec);
    // Multiple Importance Sample (MIS)
    float bsdfPdf = BSDF_PDF(L, ray, rec);
    float misWeight = PowerHeuristic(1, lightPdf, 1, bsdfPdf);

    return (f * Li * hdriExposure) / lightPdf * misWeight;
}

float HDRI_PDF(vec3 dir) {
    ivec2 size = textureSize(hdri, 0);
    int width = size.x, height = size.y;

    // Convert to spherical coordinates
    float phi = atan(dir.z, dir.x);
    float theta = acos(dir.y);
    // Convert to uv coordinates
    vec2 uv = vec2(phi / (2.0 * PI) + 0.5, theta / PI);

    int col = int(uv.x * float(width));
    int row = int(uv.y * float(height));

    float rowHigh = texelFetch(hdriRowCDF, ivec2(0, row), 0).r;
    float rowLow = row > 0 ? texelFetch(hdriRowCDF, ivec2(0, row - 1), 0).r : 0.0;
    float rowPdf = max(rowHigh - rowLow, 1e-8);
    
    float colHigh = texelFetch(hdriColCDF, ivec2(col, row), 0).r;
    float colLow = col > 0 ? texelFetch(hdriColCDF, ivec2(col - 1, row), 0).r : 0.0;
    float colPdf = max(colHigh - colLow, 1e-8);

    float mapPdf = rowPdf * colPdf * float(width) * float(height);
    float sinTheta = sin(theta);
    return sinTheta > 0.0 ?  mapPdf / (2.0 * PI * PI * sinTheta) : 0.0;
}

// https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Khronos/KHR_lights_punctual/README.md
// https://www.pbr-book.org/4ed/Light_Sources/Point_Lights
vec3 SamplePunctualLight(HitRecord rec, Ray ray, Light light, inout uvec3 v) {
    vec3 L = normalize(light.pos - rec.point);
    float dist = length(light.pos - rec.point);
    vec3 Li;
    // Point
    if (light.type == 0) {
        Li = light.col * light.intensity / max(dist * dist, 0.0001);
    }
    // Directional
    else if (light.type == 1) {
        L = normalize(-light.dir);
        dist = INF;
        Li = light.col * light.intensity;
    }
    // Spot
    else if (light.type == 2) {
        float lightAngleScale = 1.0 / max(0.001, cos(light.innerConeAngle) - cos(light.outerConeAngle));
        float lightAngleOffset = -cos(light.outerConeAngle) * lightAngleScale;

        float cd = dot(normalize(-light.dir), L);
        float angularAttenuation = clamp(cd * lightAngleScale + lightAngleOffset, 0.0, 1.0);
        angularAttenuation *= angularAttenuation;
        float attenuation = angularAttenuation / max(dist * dist, 0.0001);

        Li = light.col * light.intensity * attenuation;
    }

    vec3 N = rec.normal;
    
    float NdotL = dot(N, L);
    
    if (rec.mat.transmission == 0.0 && NdotL <= 0.0) {
        return vec3(0.0);
    }

    // Shadow ray
    Ray shadowRay;
    shadowRay.orig = rec.point + rec.geoNormal * EPSILON;
    shadowRay.dir = L;

    ShadowRecord shadowRec;
    bool occluded = TestVisibility(v, shadowRay, shadowRec);
    if (occluded && shadowRec.t < dist) {
        return vec3(0.0); // Occluded
    }

    vec3 f = EvaluateBSDF(L, ray, rec);
    return f * Li;
}

vec3 SampleAreaLight(HitRecord rec, Ray ray, inout uvec3 v) {
    int numEmissive = emissiveTriangles.length();
    if (numEmissive == 0) {
        return vec3(0.0);
    }

    vec3 Xi = PCG3d(v);

    // Uniformly sample random emissive triangle
    int emissiveTriIdx = int(Xi.x * float(numEmissive));
    int triIdx = emissiveTriangles[emissiveTriIdx].triIdx;
    Triangle tri = triangles[triIdx];

    // Uniformly sample random point on triangle
    // https://pbr-book.org/4ed/Shapes/Triangle_Meshes#Sampling
    float b0, b1, b2;
    if (Xi.y < Xi.z) {
        b0 = Xi.y / 2.0;
        b1 = Xi.z - b0;
        b2 = 1.0 - b0 - b1;
    } else {
        b1 = Xi.z / 2.0;
        b0 = Xi.y - b1;
        b2 = 1.0 - b0 - b1;
    }
    vec3 p = b0 * tri.v0.pos + b1 * tri.v1.pos + b2 * tri.v2.pos;
    vec3 lightNormal = normalize(b0 * tri.v0.normal + b1 * tri.v1.normal + b2 * tri.v2.normal);

    vec3 L = normalize(p - rec.point);
    float dist = length(p - rec.point);

    vec3 N = rec.normal;

    // Check if ray hit light's backface
    float cosLight = dot(lightNormal, -L);
    if (cosLight <= 0.0) {
        return vec3(0.0);
    }
    
    float NdotL = dot(N, L);
    
    if (rec.mat.transmission == 0.0 && NdotL <= 0.0) {
        return vec3(0.0);
    }

    // Shadow ray
    Ray shadowRay;
    shadowRay.orig = rec.point + rec.geoNormal * EPSILON;
    shadowRay.dir = L;

    // Tested value which currently works to prevent self-intersection
    float offset = EPSILON * 10.0;

    ShadowRecord shadowRec;
    bool occluded = TestVisibility(v, shadowRay, shadowRec);
    if (occluded && shadowRec.t < dist - offset) {
        return vec3(0.0); // Occluded
    }

    float pdfTri = 1.0 / float(numEmissive);
    float pdfPoint = (dist * dist) / (cosLight * tri.area);
    float lightPdf = pdfTri * pdfPoint;

    Material lightMat = materials[tri.matId];

    vec3 f = EvaluateBSDF(L, ray, rec);
    // Multiple Importance Sample (MIS)
    float bsdfPdf = BSDF_PDF(L, ray, rec);
    float misWeight = PowerHeuristic(1, lightPdf, 1, bsdfPdf);

    return (f * lightMat.emissive * lightMat.emissiveStrength) / lightPdf * misWeight;
}

vec3 RayColor(Ray ray, inout uvec3 v, out vec3 baseColorOut, out vec3 normalOut, out float depthOut) {
    HitRecord rec;

    rec.mat.ior = 1.0;

    vec3 throughput = vec3(1.0);
    vec3 radiance = vec3(0.0);

    // Entry point of a ray travelling through a medium
    vec3 entryPoint = vec3(0.0);
    bool insideMedium = false;

    bool isFirstHit = true;

    baseColorOut = vec3(0.0);
    normalOut = vec3(0.0);
    depthOut = 0.0;

    float prevBsdfPdf = 0.0;
    vec3 prevPoint = vec3(0.0);

    for (int i = 0; i < maxBounces; i++) {
        if (!Hit(ray, rec)) {
            // Ray has exited the scene
            vec3 envColor = SampleHDRI(ray.dir);
            if (isFirstHit) {
                radiance += throughput * envColor * hdriExposure;
            } else {
                float lightPdf = HDRI_PDF(ray.dir);
                float misWeight = PowerHeuristic(1, prevBsdfPdf, 1, lightPdf);
                radiance += throughput * envColor * hdriExposure * misWeight;
            }
            break;
        }

        Triangle tri = triangles[rec.triIdx];

        float u = rec.baryU;
        float vv = rec.baryV;

        vec3 e1 = tri.v1.pos - tri.v0.pos;
        vec3 e2 = tri.v2.pos - tri.v0.pos;

        float w = 1.0 - u - vv;
        vec2 texCoords = w * tri.v0.uv + u * tri.v1.uv + vv * tri.v2.uv;

        vec3 geoNormal = normalize(cross(e1, e2));
        vec3 normal = normalize(w * tri.v0.normal + u * tri.v1.normal + vv * tri.v2.normal);
        vec3 tangent = normalize(w * tri.v0.tangent + u * tri.v1.tangent + vv * tri.v2.tangent);
        vec3 bitangent = normalize(w * tri.v0.bitangent + u * tri.v1.bitangent + vv * tri.v2.bitangent);
        
        bool backFace = dot(geoNormal, ray.dir) > 0.0;

        if (backFace) {
            geoNormal = -geoNormal;
            normal = -normal;
            tangent = -tangent;
            bitangent = -bitangent;
        }

        rec.TBN = mat3(tangent, bitangent, normal);
        rec.InvTBN = transpose(rec.TBN);

        Material mat = materials[tri.matId];

        float eta = backFace ? mat.ior / 1.0 : 1.0 / mat.ior;
        
        rec.point = GetRayPoint(ray, rec.t);
        rec.geoNormal = geoNormal;
        rec.normal = normal;
        rec.tangent = tangent;
        rec.bitangent = bitangent;
        rec.uv = texCoords;
        rec.eta = eta;
        rec.backFace = backFace;
        rec.triArea = tri.area;

        if (mat.hasBaseColTex == 1) {
            vec4 baseCol = texture(baseColorTextures, vec3(rec.uv, mat.baseTexId));
            mat.baseCol = baseCol.rgb;
            mat.alpha = baseCol.w;
        }
        if (mat.hasEmissiveTex == 1) {
            mat.emissive = texture(emissiveTextures, vec3(rec.uv, mat.emissiveTexId)).rgb;
        }
        if (mat.hasRoughTex == 1) {
            mat.roughness = texture(roughnessTextures, vec3(rec.uv, mat.roughTexId)).r;
        }
        if (mat.hasMetalTex == 1) {
            mat.metallic = texture(metallicTextures, vec3(rec.uv, mat.metalTexId)).r;
        }
        // https://learnopengl.com/Advanced-Lighting/Normal-Mapping
        if (mat.hasNormalTex == 1) {
            mat3 TBN = mat3(rec.tangent, rec.bitangent, rec.normal);
            // Get normal in world space
            vec3 normal = texture(normalTextures, vec3(rec.uv, mat.normalTexId)).rgb;
            normal = normal * 2.0 - 1.0;
            rec.normal = normalize(TBN * normal);

            vec3 N = rec.normal;

            // Build an Orthonormal basis (ONB)
            vec3 helper = abs(N.z) > 0.999 ? vec3(0, 1, 0) : vec3(0, 0, 1);
            vec3 T = normalize(cross(helper, N));
            vec3 B = cross(N, T);

            rec.TBN = mat3(T, B, N);
            rec.InvTBN = transpose(rec.TBN);
        } else {
            vec3 N = rec.normal;

            // Build an Orthonormal basis (ONB)
            vec3 helper = abs(N.z) > 0.999 ? vec3(0, 1, 0) : vec3(0, 0, 1);
            vec3 T = normalize(cross(helper, N));
            vec3 B = cross(N, T);

            rec.TBN = mat3(T, B, N);
            rec.InvTBN = transpose(rec.TBN);
        }
        
        // Add light contribution
        if (mat.hasEmission == 1) {
            if (isFirstHit) {
                radiance += throughput * mat.emissive * mat.emissiveStrength;
            } else {
                // Multiple Importance Sample (MIS)
                float lightPdf = LightPDF(rec, ray, prevPoint);
                float misWeight = PowerHeuristic(1, prevBsdfPdf, 1, lightPdf);
                radiance += throughput * mat.emissive * mat.emissiveStrength * misWeight;
            }
        }

        if (mat.alphaMode == 1) {
            // MASK
            if (mat.alpha < mat.alphaCutoff) {
                // Advance the ray and ignore the hit
                ray.orig = rec.point + ray.dir * EPSILON;
                continue;
            }
        }
        float blendRand = PCG3d(v).x;
        if (mat.alphaMode == 2) {
            // BLEND
            if (PCG3d(v).x > mat.alpha) {
                // Advance the ray and ignore the hit
                ray.orig = rec.point + ray.dir * EPSILON;
                continue;
            }
        }

        // Prevent 0 roughness which results in NaN in many functions
        mat.roughness = max(mat.roughness, 1e-2);

        rec.mat = mat;

        vec3 direct = vec3(0.0);
        for (int li = 0; li < lights.length(); li++) {
            direct += SamplePunctualLight(rec, ray, lights[li], v);
        }
        direct += SampleAreaLight(rec, ray, v);
        direct += SampleHDRILight(rec, ray, v);

        radiance += throughput * direct;

        vec3 bounceDir;
        float bsdfPdf;
        vec3 bsdf = SampleBSDF(v, ray, rec, bounceDir, bsdfPdf);

        if (isFirstHit) {
            baseColorOut = mat.baseCol;
            normalOut = rec.normal;
            // Subtract from 1 as depth color reduces with distance
            float depth = 1.0 - rec.t * depthFactor / 2.0;
            depthOut = clamp(depth, 0.0, 1.0);

            isFirstHit = false;
        }

        prevBsdfPdf = bsdfPdf;
        prevPoint = rec.point;

        bool didRefract = dot(bounceDir, rec.geoNormal) < 0.0;

        vec3 transmittance;
        BeerLambert(insideMedium, entryPoint, rec, transmittance, didRefract);

        throughput *= transmittance;
        throughput *= bsdf;

        ray.dir = bounceDir;

        vec3 offsetDir = didRefract ? -rec.geoNormal : rec.geoNormal;
        ray.orig = rec.point + offsetDir * EPSILON;

        // Russian Roulette
        // https://pbr-book.org/3ed-2018/Monte_Carlo_Integration/Russian_Roulette_and_Splitting

        if (i > 3) {
            // Termination probability
            float q = 1.0 - max(throughput.r, max(throughput.g, throughput.b));
            float xi = PCG3d(v).x;

            if (xi < q) {
                // Return radiance so far
                break;
            } else {
                throughput = throughput / (1.0 - q);
            }
        }
    }

    return radiance;
}

uvec3 InitRngState(ivec2 pixelCoords) {
    uvec3 state = uvec3(
        (pixelCoords.x) * 1512558u,
        uint(pixelCoords.y) * 1029858u,
        uint(totalSamples) * 739391335u
    );

    state ^= uvec3(1597334677u, 3812015801u, 2798796415u);

    return state;
}

vec2 SampleUnitDisk(inout uvec3 v) {
    vec3 r = PCG3d(v);
    float theta = 2.0 * PI * r.x;
    float radius = sqrt(r.y);
    return vec2(radius * cos(theta), radius * sin(theta));
}

void main() {
    ivec2 pixelCoords = uOffset + ivec2(gl_GlobalInvocationID.xy);
    ivec2 dims = imageSize(combinedPass);

    // Only render pixels in frame
    if (pixelCoords.x >= dims.x || pixelCoords.y >= dims.y) return;

    uvec3 state = InitRngState(pixelCoords);
    
    float maxRadiance = 100.0;

    vec3 sampleCombined = vec3(0.0);
    vec3 sampleBaseColor = vec3(0.0);
    vec3 sampleNormal = vec3(0.0);
    float sampleDepth = 0.0;
    for (int i = 0; i < samplesPerPixel; i++) {
        // Get random vec3 (range [0, 1])
        // Convert to range [-0.5, 0.5]
        vec3 noise = PCG3d(state) - 0.5;
        // Anti-aliasing sub-pixel jitter
        vec2 jitter = noise.xy * blur;

        // Map pixel to Normalized Device Coordinates (-1 to 1)
        vec2 uv = (vec2(pixelCoords) + jitter) / vec2(dims) * 2.0 - 1.0;

        // Adjust for aspect ratio
        uv.x *= aspectRatio;

        float tanHalfFov = tan(radians(Camera.fov) * 0.5);
        vec3 pinholeDir = normalize(Camera.front + (uv.x * Camera.right * tanHalfFov) + (uv.y * Camera.up * tanHalfFov));

        vec3 focusPoint = Camera.pos + pinholeDir * Camera.focusDist;

        vec2 rd = Camera.aperture * SampleUnitDisk(state);
        vec3 offset = Camera.right * rd.x + Camera.up * rd.y;

        Ray ray;
        ray.orig = Camera.pos + offset;
        ray.dir = normalize(focusPoint - ray.orig);

        vec3 baseColorOut;
        vec3 normalOut;
        float depthOut;
        vec3 newColor = RayColor(ray, state, baseColorOut, normalOut, depthOut);

        // Clamp to prevent fireflies
        sampleCombined += min(newColor, vec3(maxRadiance));
        sampleBaseColor += baseColorOut;
        sampleNormal += normalOut;
        sampleDepth += depthOut;
    }
    sampleCombined /= float(samplesPerPixel);
    sampleBaseColor /= float(samplesPerPixel);
    sampleNormal /= float(samplesPerPixel);
    sampleDepth /= float(samplesPerPixel);

    vec3 oldCombined = imageLoad(combinedPass, pixelCoords).rgb;
    vec3 oldBaseColor = imageLoad(baseColorPass, pixelCoords).rgb;
    vec3 oldNormal = imageLoad(normalPass, pixelCoords).rgb;
    float oldDepth = imageLoad(depthPass, pixelCoords).r;
    float weight = float(samplesPerPixel) / (float(totalSamples + samplesPerPixel));
    
    vec3 finalCombined;
    vec3 finalBaseCol;
    vec3 finalNormal;
    float finalDepth;
    if (totalSamples == 0) {
        // Ignore old color
        finalCombined = sampleCombined;
        finalBaseCol = sampleBaseColor;
        finalNormal = sampleNormal;
        finalDepth = sampleDepth;
    } else {
        finalCombined = mix(oldCombined.rgb, sampleCombined, weight);
        finalBaseCol = mix(oldBaseColor.rgb, sampleBaseColor, weight);
        finalNormal = mix(oldNormal.rgb, sampleNormal, weight);
        finalDepth = mix(oldDepth.r, sampleDepth, weight);
    }
    
    imageStore(combinedPass, pixelCoords, vec4(finalCombined, 1.0));
    imageStore(baseColorPass, pixelCoords, vec4(finalBaseCol, 1.0));
    imageStore(normalPass, pixelCoords, vec4(finalNormal, 1.0));
    imageStore(depthPass, pixelCoords, vec4(vec3(finalDepth), 1.0));
}
